### ISSUE TITLE
Model: Transfer Learning Model (Model maker)

### ISSUE THREAD

**Issue by kaqreal** [kaqreal/ds-Capstone_Fish_Project#10]

**Comment by niels-lory** [comment]
https://www.tensorflow.org/hub 

https://keras.io/api/applications/#:~:text=Keras%20Applications%20are%20deep%20learning,They%20are%20stored%20at%20~%2F.

https://pytorch.org/vision/stable/models.html

https://github.com/Cadene/pretrained-models.pytorch

https://github.com/onnx/models

https://github.com/deepset-ai/FARM

https://awesomeopensource.com/projects/pretrained-models

**Comment by kaqreal** [comment]
convolutional neural networks (CNNs)
support vector machines (SVMs)
random forests (RFs)

so we dont loose it
